# Directory where the files are located
work_dir: "/mnt/esb-storage-01/NOMIS/LAO_reads_isolate"

# Directory where the results are to be stored
results_dir: "/mnt/esb-storage-01/NOMIS/LAO_reads_isolate/PolyGFS_results"

# Directory where conda environments are located
env_dir: "/mnt/data/sbusi/PolyGFS/envs"

# Directory with scripts for analyses
scripts_dir: "/mnt/data/sbusi/PolyGFS/scripts"

# Directory with the bins of interest
bin_dir: "/mnt/esb-storage-01/NOMIS/LAO_reads_isolate"

# Directory with the preprocessed FASTQ reads
fastq_dir: "/mnt/esb-storage-01/NOMIS/LAO_reads_isolate"

##########
# Params #
bwa:
  threads: 24
  sort: 
    threads: 6
    chunk_size: "4G"
  vcf:
    threads: 8
