############################################################
# STEPS

# Steps to be done
# steps: ["imp"]  # RUN THIS FIRST and launch IMP3 outside of the workflow

# Next the following steps should be run
steps: ["dn_genomes", "drep_mags", "collect_mags", "phylo_analysis"]#, "comp_matrix", "annotate_genomes", "pan_genome", "map_reads", "var_calling"]


############################################################
# INPUT

# Directory where the files are located
work_dir: "/mnt/md1200/epfl_sber/massimo/ChapterII/PolyGFS"

# Directory where the results are to be stored
results_dir: "/mnt/md1200/epfl_sber/massimo/ChapterII/results"

# Directory where conda environments are located
env_dir: "/mnt/md1200/epfl_sber/massimo/ChapterII/PolyGFS/envs"

# Directory with scripts for analyses
scripts_dir: "/mnt/md1200/epfl_sber/massimo/ChapterII/PolyGFS/workflow/scripts"

# Directory with the bins of interest
mags_dir: "/mnt/esb-storage-01/NOMIS/ROCKS/rock_bins"

# Directory with the preprocessed FASTQ reads
fastq_dir: "/mnt/esb-storage-01/NOMIS/coassembly/preproc"

# Directors of the gtdbtk database
gtdbtk_db_dir: "/mnt/esb-storage-01/NOMIS/databases/release202"

##########
# Params #
dn_genomes:
  thread: 8

gtdbtk:
  path: "/mnt/esb-storage-01/NOMIS/databases/release202"
  threads: 32

drep:
  threads: 32

checkm:
  db_path: "/mnt/esb-storage-01/NOMIS/databases"

bwa:
  threads: 24
  sort: 
    threads: 4
    chunk_size: "4G"
  vcf:
    threads: 8

# Set of HMM to use for Gtotree
gtotree:
  hmm: 'Gammaproteobacteria'
  threads: 32

# Prokka
prokka:
  threads: 12

# MANTIS
mantis:
  cores: 4
  hmmer_threads: 1
  single_mem: 200
  multi_mem: 500
  path: "/mnt/esb-storage-01/NOMIS/databases/mantis"
  # default HMMs
  default:
    kofam_hmm_folder: "/mnt/esb-storage-01/NOMIS/databases/mantis/hmm/kofam_mantis"
    ncbi_hmm_folder: "/mnt/esb-storage-01/NOMIS/databases/mantis/hmm/NCBI"
    nog_hmm_folder: "/mnt/esb-storage-01/NOMIS/databases/mantis/hmm/eggnog_mantis/NOGT"
    pfam_hmm_folder: "/mnt/esb-storage-01/NOMIS/databases/mantis/hmm/pfam"
    tigrfam_hmm_folder: "/mnt/esb-storage-01/NOMIS/databases/mantis/hmm/tigrfam"
  # custom HMMs
#  custom: [
#    "/mnt/isilon/projects/ecosystem_biology/data/hmm/Cas/Burstein2016.Nature.Cas_db.hmm",
#    "/mnt/isilon/projects/ecosystem_biology/data/hmm/HMM2015/BRENDA/brenda.hmm",
#    "/mnt/isilon/projects/ecosystem_biology/data/hmm/HMM2015/metacyc/metacyc.hmm",
#    "/mnt/isilon/projects/ecosystem_biology/data/hmm/HMM2015/SwissProt/swissprot.hmm",
#    "/mnt/isilon/projects/ecosystem_biology/data/hmm/transportdb/transportdb_merged.hmm",
#    "/mnt/isilon/projects/ecosystem_biology/data/hmm/resfams/Resfams-full.hmm"
#  ]
  # weights: <name>_hmm_folder --> <name>_weight
  weights:
    ncbi_weight: 0.9
    nog_weight: 0.8
    pfam_weight: 0.9
    tigrfam_weight: 0.5




