############################################################
# STEPS

# Steps to be done
# steps: ["imp"]  # RUN THIS FIRST and launch IMP3 outside of the workflow

# Next the following steps should be run
steps: ["dn_genomes"]#, "drep_mags", "phylo_analysis", "comp_matrix", "annotate_genomes", "pan_genome", "map_reads", "var_calling"]


############################################################
# INPUT

# Directory where the files are located
work_dir: "/mnt/md1200/epfl_sber/massimo/ChapterII/PolyGFS"

# Directory where the results are to be stored
results_dir: "/mnt/md1200/epfl_sber/massimo/ChapterII/results"

# Directory where conda environments are located
env_dir: "/mnt/md1200/epfl_sber/massimo/ChapterII/PolyGFS/envs"

# Directory with scripts for analyses
scripts_dir: "/mnt/md1200/epfl_sber/massimo/ChapterII/PolyGFS/workflow/scripts"

# Directory with the bins of interest
mags_dir: "/mnt/esb-storage-01/NOMIS/ROCKS/rock_bins/"

# Directory with the preprocessed FASTQ reads
fastq_dir: "/mnt/esb-storage-01/NOMIS/coassembly/preproc"

# Directors of the gtdbtk database
gtdbtk_db_dir: "/mnt/esb-storage-01/NOMIS/databases/release202"

##########
# Params #
dn_genomes:
  thread: 8

gtdbtk:
  path: "/mnt/esb-storage-01/NOMIS/databases/release202"
  threads: 32

bwa:
  threads: 24
  sort: 
    threads: 4
    chunk_size: "4G"
  vcf:
    threads: 8

# Set of HMM to use for Gtotree
gtotree:
  hmm: 'Gammaproteobacteria'
